### ISSUE TITLE
suggestion for dark theme

### ISSUE THREAD

**Issue by incantatem1** [sr-campelo/retronotes#2]
could you make a dark theme that's based on dull purple / amethyst color palette? i don't really like any of the available dark theme options T_T

**Comment by sr-campelo** [comment]
I added a new color scheme named Pinot Noir. You must reinstall the theme to see the new style settings configurations.
If you like it I will close the issue and release version 1.0.2 with this new theme and add your name as collaborator.

**Comment by incantatem1** [comment]
hmm, nice palette, i hoped for something more purple though XD i don't know if you want to overwork it again, maybe you can keep this one since it's not bad either and just add another one that's more actually purple? like something with this as main color https://hexcolor.co/hex/443955 and this as accent/font https://hexcolor.co/hex/e6e6fa ? (not sure which combinations would look best there so it's not too much eyestrain.)

thank you for your work!

**Comment by sr-campelo** [comment]
Perfect, I will work on a new one based on those colors. Since it will be your personalized color scheme you can choose the name 😉

**Comment by incantatem1** [comment]
oh, hmm. i'm super bad with choosing names, lol. i'll think of something.

**Comment by incantatem1** [comment]
ok, i have an idea, how about "misty mirage"?

**Comment by sr-campelo** [comment]
I added Misty Mirage color scheme (you must reinstall the theme to see it).
Let me know if you like it.

**Comment by incantatem1** [comment]
aah, that's lovely T_T

beautiful and unusual dark theme, yes, i like it!

**Comment by sr-campelo** [comment]
Glad you like it. It's for you. Thanks for contributing to this theme 🤍

**Comment by nicosomb** [comment]
A dark theme with a light sidebar, love it!
